version: '2.2'
services:

  elasticsearch: # <<< 1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
    networks:
      - elastic
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana: # <<< 2
    image: docker.elastic.co/kibana/kibana:7.8.1
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

  fluentd: # <<< 3
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    networks:
      - elastic
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  web: # <<< 4
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.web"
    networks:
      - elastic


networks:
  elastic:
    driver: bridge